version: '3.8'
services:
  app:
    build: .
    container_name: desafio-salles-app
    ports:
      - "8081:8080"
    depends_on:
      - db
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/contas_db
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_FLYWAY_ENABLED: true
    networks:
      - desafio-network

  db:
    image: postgres:14-alpine
    container_name: desafio-salles-db
    environment:
      POSTGRES_DB: contas_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"
    networks:
      - desafio-network

networks:
  desafio-network:
    driver: bridge
